export const labels = {
    logIn: "Log in",
    logOut: "Log out",
    loading: "Loading",
    rolesList: "Roles",
    selectRole: "Select role",
    couldNotLoadAccounts: "Could not load accounts",
    thisIsAFreeSoftware: "This program is a free software",
    getSource: "get source",
    error: "error",
    name: "Name",
    actions: "Actions",
    uid: "User id",
    email: "Email",
    request: "Request",
    confirmRoleRequest: "Confirm role request",
    rejectRoleRequest: "Reject role request",
    confirmRoleRequestTemplate: "Do you want to grant role '$role' to user '$displayName <$email>' (uid: $uid)?",
    rejectRoleRequestTemplate:
        "Do you want to reject role '$role' request by user '$displayName <$email>' (uid: $uid)?",
    grant: "Grant",
    cancel: "Cancel",
    reject: "Reject",
    successfullyGrantedRole: "Successfully granted role",
    successfullyRejectedRole: "Successfully rejected role",
};
