export const labels = {
    logIn: "Log in",
    logOut: "Log out",
    loading: "Loading",
    rolesList: "Roles",
    selectRole: "Select role",
    couldNotLoadAccounts: "Could not load accounts",
    thisIsAFreeSoftware: "This program is a free software",
    getSource: "get source",
    error: "error",
    name: "Name",
    actions: "Actions",
    uid: "User id",
    email: "Email",
};
